### PR TITLE
Added other verbs for HTTP requests.

### LINKED ISSUE #32: When will be support http method PATCH?
What version will be support this?

### PR DESCRIPTION
**Pull request by benhowes**
Closes #32.

### CODE REVIEW

**Comment by michaelboulton** [comment]
Do all of these methods behave like a post request (eg, stuff sent in the post body)? There is a check to stop you sending a body in a GET request, wondering if there should be something like this for any of these methods (eg options) https://github.com/taverntesting/tavern/blob/f7448cd1f7bc5319d12a4f1ac90d95fcb63d8f24/tavern/request.py#L110-L112

The only reason all the verbs weren't included in the original response is I don't know about the semantics of them

**Comment by benhowes** [comment]
@michaelboulton that's a good point. Most can, infact in some horrible cases (e.g. Elastic Search) it is possible to send a body on a GET request even. I will check up on it later.

**Comment by benhowes** [comment]
As discussed, it's probably best if we don't enforce no bodies at all, but we can warn on `OPTIONS`, `GET,` and `HEAD` since they're not expected to have bodies (as per: https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods)

**Comment by benhowes** [comment]
@michaelboulton

**Pull request merged**
