### PR TITLE
Replace deprecated `pytest.warns(None)`

### PR DESCRIPTION
**Pull request by mgorny**
Replace the deprecated `pytest.warns(None)` use with the `error` warning filter, as recommended
in https://github.com/pytest-dev/pytest/issues/9404#issue-1076710891. With this change, the tests pass with pytest-8.1.1.

### CODE REVIEW

**Comment by mgorny** [comment]
Alternatively, I can change it to use `warnings.catch_warnings(record=True)` or the `recwarn` fixture, and continue to check for zero recorded warnings.

**Comment by michaelboulton** [comment]
> Alternatively, I can change it to use `warnings.catch_warnings(record=True)` or the `recwarn` fixture, and continue to check for zero recorded warnings.

I think it's best to do this

**Comment by mgorny** [comment]
I'm sorry, which one?

**Comment by michaelboulton** [comment]
> I'm sorry, which one?

Probably the first one, seems like that makes the most sense.

**Comment by mgorny** [comment]
I've updated the pull request now.

**Review by michaelboulton — APPROVED** [review]

**Comment by mgorny** [comment]
Thanks!

**Pull request merged**
