### PR TITLE
Feature/fixtures

### PR DESCRIPTION
**Pull request by michaelboulton**
This just reuses the `usefixtures` mark so you can specify a list of fixture names to use for that test. This can be used with 'yielding' fixtures to run stuff before and after the test stage, and the return value of any fixtures is added to the variables for that test. For example, this fixture:

```python
@pytest.fixture(name="json_val")
def get_json_val():
    return "abc123"
```

will be put into the variables as `{"json_val": "abc123"}` for use in formatting.

### CODE REVIEW

**Comment by michaelboulton** [comment]
It might be worth modifying this slightly before merging so that it can add context to the whole test as well. It is technically possible with this PR to write a fixture like this:

```python
@pytest.fixture(name="use_tavern_flask")
def add_flask_spec(request):
    request._pyfuncitem.spec["flask"] = {"app": ....}
```

but maybe exposing that properly and making it the 'preferred' way of doing it would be good and would fix #113. Thoughts @benhowes @Birne94  ?

**Comment by Birne94** [comment]
How do you feel about introducing a special `tavern` fixture which provides access to different helper methods? These could include setting plugin config, global variables etc.

This would give tavern more control over what can be manipulated in contrast to letting the user manipulate the dictionaries at will and maybe causing cryptic/hard to track errors as a result.

**Comment by Birne94** [comment]
Also, while testing I noticed that the fixture scope `module` does not work with tavern currently. `function` and `session` work as expected.

This can be resolved by changing the base class of `YamlFile` (`tavern/testutils/pytesthook.py`) to `pytest.Module`. `Module` itself is subclass of `pytest.File`, so no behavior should change here.

I am not sure if the additional logic in the `Module` class can cause any trouble, though.

**Comment by michaelboulton** [comment]
How would you expect the scopes to work? I wasn't really thinking about it while implementing this, would the 'module' be the whole file?

**Comment by Birne94** [comment]
By default pytest supports the following scopes:

- session
- module
- class
- function

The `class` session would not make too much sense with tavern, I guess, but `module` would be nice to have in order to setup a common ground for related tests and avoid having to allocate resources multiple times. Since tavern allows defining multiple tests in a single file, I would consider this file a module. This also matches the default behavior of each file being a module.

The other ones (`function` and `session`) work through the default implementation.

**Comment by michaelboulton** [comment]
I suppose it probably works when you inherit from `Module` because it keys the tests on the `fspath` rather than `name`? It seems to not raise any errors but it seems like it might cause some weird errors with fixtures seeing as Tavern doesn't really map to the concept of modules or functions

**Comment by michaelboulton** [comment]
It might be worth actually checking so that if fixtures don't have either 'session' or 'function' scope then it raises an error

**Comment by michaelboulton** [comment]
Trying to use a module scoped fixture fails anyway, and class fixtures seem to just be regenerated between tests, so I think that should be fine as it is

**Pull request merged**
