### PR TITLE
support ignore field in a stage

### PR DESCRIPTION
**Pull request by theonlyx**
Enable `ignore` of a step in a multiple stages test. 

If the `ignore` field is defined and it's value is `True`, ignore that step.

### CODE REVIEW

**Comment by theonlyx** [comment]
https://github.com/taverntesting/tavern/issues/468

**Comment by michaelboulton** [comment]
Is this any different to the `skip` options which currently exists (https://tavern.readthedocs.io/en/latest/basics.html#skip)?

**Comment by theonlyx** [comment]
> Is this any different to the `skip` options which currently exists (https://tavern.readthedocs.io/en/latest/basics.html#skip)?

`skip` skips the entire test, not for any particular step. For example, if a test contains steps `A`, and `B`. `C`. `skip` cannot be used to skip one step such as `B`.

**Comment by michaelboulton** [comment]
The 'skip' marker skips a whole test, but `skip: True` can also be put in a stage to skip just that stage

**Comment by theonlyx** [comment]
> The 'skip' marker skips a whole test, but `skip: True` can also be put in a stage to skip just that stage

Obviously I overlooked that feature. Thank you!

**Pull request closed without merging**
