### PR TITLE
Consider TypeTokens valid types when validating schema

### PR DESCRIPTION
**Pull request by tommilligan**
See issue #153 for description

### CODE REVIEW

**Comment by tommilligan** [comment]
Added three failing tests that show `tavern` variables cannot be used as part of `pykwalify` validated schema. This makes sense, as at validation time these fields will be `Tokens` rather than the primitive types they promise.

The above commits allow all `bool` values in the current test schema to be variables, fixing one failing test. Before I fix the others thought I'd get some feedback.

**Details**
I initially tried using `isinstance` to extend class checks, but this threw up bugs (e.g. pykwalify allows integers to count as floats). So, I've just extended pykwalify's [type check functions](https://github.com/Grokzen/pykwalify/blob/a41db86ebfb9a0ef00d7682efe7a29b76b052289/pykwalify/types.py#L76) to [include `Tokens`](https://github.com/taverntesting/tavern/pull/154/files#diff-d5fe3ada6f9cf0cb9db3de78db3f3fb6R21). It works nicely!

To accept `tavern` variables as part of a schema file, we use `pykwalify` extension syntax:
```yaml
# Allows boolean primitive only
verify:
  type: bool

---

verify: False
```
becomes
```yaml
# Allows boolean primitive or boolean variable
verify:
  type: any
  func: bool_variable

---

verify: "{v_false}"
```

Other schemas will have to opt-in to this approach. If no changes are made to the schema, variables will be invalid.

**Comment by tommilligan** [comment]
@michaelboulton could I get some feedback on whether you'd be happy with the above approach, before I progress it any further?

**Comment by michaelboulton** [comment]
It looks fine to me, I'm just not sure what you mean by:

> Other schemas will have to opt-in to this approach

You mean schema for plugins?

**Comment by tommilligan** [comment]
Yes, exactly. Any schema that uses the pykwalify builtin types `bool`, `int`, `float` etc. would fail validation if given variables. Schema writers would have to explicitly use `bool_variable` etc. to allow variables as well.

**Comment by ke4roh** [comment]
This appears to be the actual issue I remarked about in a recent comment on Issue #149.  Allow me to offer my enthusiastic support for this PR.

**Comment by benhowes** [comment]
@tommilligan I know this one is quite old, but are you in a position that you could take a look so we can get this merged in?

**Comment by benhowes** [comment]
@tommilligan ping!

**Comment by tommilligan** [comment]
@benhowes ready for final review. It's slightly messy as there's not a single point in the code where variables are resolved. I'm happy it will fix _most_ issues, but not certain it will catch _all_ of them.

Essentially:
- when variables are part of the schema, they are loaded as python `Token` instances
- we use functions like `is_float_like` to check them in python
- we use functions like `int_variable` to check them in the pykwalify yaml schema

See above for how this will affect custom schemas.

**Comment by michaelboulton** [comment]
closes #153

**Comment by michaelboulton** [comment]
Thanks a lot for this, this should fix most of the lingering annoying issues with type tokens in various situations.

**Pull request merged**
